### PR TITLE
Here are the makefiles and some other cleanup

### PR DESCRIPTION
**Pull request by sonninnos**
Was a bit of a hassle to get and keep my version up to date, but ahm learning.

Is there a way to request just some certain commits and not all at once?

### CODE REVIEW

**Comment by rsn8887** [comment]
Awesome but Something is weird can you rebase your branch on top of my master and force push to remove duplicate commits? You can make a backup branch ‘git branch backup’ it be safe

**Comment by rsn8887** [comment]
Or better: rebase your branch on top of upstream master and make a PR there.

**Comment by rsn8887** [comment]
I removed you as collaborator because I frequently force push here and it would cause problems for both of us commiting together.

**Comment by rsn8887** [comment]
Are you on discord or can you join Libretro discord server, channel Retroarch? We could chat later I am on there.

**Comment by sonninnos** [comment]
Sorry for the hassle, but maybe now I succeeded.

**Pull request closed without merging**
